// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CategoryInKitchenScreenSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'CategoryInKitchenScreen'
} as const;

export const CategoryInProductSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'CategoryInProduct',
    description: 'Schema nhẹ cho category khi lồng trong Product response.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const KitchenScreenCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name',
            description: 'Tên màn hình nhà bếp'
        },
        pos_id: {
            type: 'string',
            format: 'uuid',
            title: 'Pos Id',
            description: 'POS áp dụng'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            description: 'Trạng thái hoạt động',
            default: true
        },
        category_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Category Ids',
            description: 'Danh mục áp dụng'
        }
    },
    type: 'object',
    required: ['name', 'pos_id'],
    title: 'KitchenScreenCreate'
} as const;

export const KitchenScreenPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name',
            description: 'Tên màn hình nhà bếp'
        },
        pos_id: {
            type: 'string',
            format: 'uuid',
            title: 'Pos Id',
            description: 'POS áp dụng'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            description: 'Trạng thái hoạt động',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        pos: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PosInKitchenScreen'
                },
                {
                    type: 'null'
                }
            ]
        },
        categories: {
            items: {
                '$ref': '#/components/schemas/CategoryInKitchenScreen'
            },
            type: 'array',
            title: 'Categories',
            default: []
        }
    },
    type: 'object',
    required: ['name', 'pos_id', 'id'],
    title: 'KitchenScreenPublic'
} as const;

export const KitchenScreenUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        pos_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pos Id'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        category_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string',
                        format: 'uuid'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Ids'
        }
    },
    type: 'object',
    title: 'KitchenScreenUpdate'
} as const;

export const KitchenScreensPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/KitchenScreenPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'KitchenScreensPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const OrderTypeCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name',
            description: 'Tên loại đơn hàng (Ví dụ: Mang đi, Tại chỗ, Grab...)'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            description: 'Trạng thái hoạt động',
            default: true
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            description: 'Lưu trữ',
            default: false
        }
    },
    type: 'object',
    required: ['name'],
    title: 'OrderTypeCreate'
} as const;

export const OrderTypePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name',
            description: 'Tên loại đơn hàng (Ví dụ: Mang đi, Tại chỗ, Grab...)'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            description: 'Trạng thái hoạt động',
            default: true
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            description: 'Lưu trữ',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'OrderTypePublic'
} as const;

export const OrderTypeUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_archived: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Archived'
        }
    },
    type: 'object',
    title: 'OrderTypeUpdate'
} as const;

export const OrderTypesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/OrderTypePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'OrderTypesPublic'
} as const;

export const PaymentMethodCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name',
            description: 'Tên phương thức thanh toán'
        },
        code: {
            type: 'string',
            maxLength: 50,
            minLength: 1,
            title: 'Code',
            description: 'Mã phương thức thanh toán'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            description: 'Lưu trữ',
            default: false
        }
    },
    type: 'object',
    required: ['name', 'code'],
    title: 'PaymentMethodCreate'
} as const;

export const PaymentMethodInPosSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        code: {
            type: 'string',
            title: 'Code'
        }
    },
    type: 'object',
    required: ['id', 'name', 'code'],
    title: 'PaymentMethodInPos'
} as const;

export const PaymentMethodPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name',
            description: 'Tên phương thức thanh toán'
        },
        code: {
            type: 'string',
            maxLength: 50,
            minLength: 1,
            title: 'Code',
            description: 'Mã phương thức thanh toán'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            description: 'Lưu trữ',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'code', 'id'],
    title: 'PaymentMethodPublic'
} as const;

export const PaymentMethodUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Code'
        },
        is_archived: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Archived'
        }
    },
    type: 'object',
    title: 'PaymentMethodUpdate'
} as const;

export const PaymentMethodsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PaymentMethodPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PaymentMethodsPublic'
} as const;

export const PosCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name',
            description: 'Tên quầy bán hàng'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            description: 'Lưu trữ',
            default: false
        },
        payment_method_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Payment Method Ids'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'PosCreate'
} as const;

export const PosInKitchenScreenSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'PosInKitchenScreen'
} as const;

export const PosPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name',
            description: 'Tên quầy bán hàng'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            description: 'Lưu trữ',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        payment_methods: {
            items: {
                '$ref': '#/components/schemas/PaymentMethodInPos'
            },
            type: 'array',
            title: 'Payment Methods',
            default: []
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'PosPublic'
} as const;

export const PosUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        is_archived: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Archived'
        },
        payment_method_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string',
                        format: 'uuid'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payment Method Ids'
        }
    },
    type: 'object',
    title: 'PosUpdate'
} as const;

export const PossPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PosPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PossPublic'
} as const;

export const PrinterCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name',
            description: 'Tên thiết bị máy in'
        },
        ip: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Ip',
            description: 'Địa chỉ IP máy in'
        },
        port: {
            type: 'integer',
            maximum: 65535,
            minimum: 1,
            title: 'Port',
            description: 'Cổng kết nối',
            default: 9100
        },
        printer_type: {
            type: 'string',
            enum: ['invoice', 'label', 'kitchen_order_ticket'],
            title: 'Printer Type',
            description: 'Loại máy in',
            default: 'invoice'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            description: 'Máy in đang hoạt động',
            default: true
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            description: 'Lưu trữ',
            default: false
        }
    },
    type: 'object',
    required: ['name', 'ip'],
    title: 'PrinterCreate'
} as const;

export const PrinterPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name',
            description: 'Tên thiết bị máy in'
        },
        ip: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Ip',
            description: 'Địa chỉ IP máy in'
        },
        port: {
            type: 'integer',
            maximum: 65535,
            minimum: 1,
            title: 'Port',
            description: 'Cổng kết nối',
            default: 9100
        },
        printer_type: {
            type: 'string',
            enum: ['invoice', 'label', 'kitchen_order_ticket'],
            title: 'Printer Type',
            description: 'Loại máy in',
            default: 'invoice'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            description: 'Máy in đang hoạt động',
            default: true
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            description: 'Lưu trữ',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'ip', 'id'],
    title: 'PrinterPublic'
} as const;

export const PrinterUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        ip: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ip'
        },
        port: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 65535,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Port'
        },
        printer_type: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['invoice', 'label', 'kitchen_order_ticket']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Printer Type'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_archived: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Archived'
        }
    },
    type: 'object',
    title: 'PrinterUpdate'
} as const;

export const PrintersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PrinterPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PrintersPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProductCategoriesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProductCategoryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProductCategoriesPublic'
} as const;

export const ProductCategoryCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name',
            description: 'Tên danh mục'
        },
        color: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 7
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color',
            description: 'Màu sắc'
        },
        image: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image',
            description: 'Hình ảnh'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description',
            description: 'Mô tả'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            description: 'Lưu trữ',
            default: false
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ProductCategoryCreate'
} as const;

export const ProductCategoryPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name',
            description: 'Tên danh mục'
        },
        color: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 7
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color',
            description: 'Màu sắc'
        },
        image: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image',
            description: 'Hình ảnh'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description',
            description: 'Mô tả'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            description: 'Lưu trữ',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'ProductCategoryPublic'
} as const;

export const ProductCategoryUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        color: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 7
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        image: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_archived: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Archived'
        }
    },
    type: 'object',
    title: 'ProductCategoryUpdate'
} as const;

export const ProductCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name',
            description: 'Tên sản phẩm'
        },
        sku: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Sku',
            description: 'Mã sản phẩm'
        },
        image: {
            type: 'string',
            maxLength: 255,
            title: 'Image',
            description: 'Hình ảnh',
            default: ''
        },
        type: {
            type: 'string',
            enum: ['consu', 'service', 'combo'],
            title: 'Type',
            description: 'Loại sản phẩm (consu: hàng hoá, service: dịch vụ, combo: bộ)',
            default: 'consu'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description',
            description: 'Mô tả'
        },
        uom_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Uom Id',
            description: 'Đơn vị tính chính'
        },
        price: {
            type: 'number',
            minimum: 0,
            title: 'Price',
            description: 'Giá bán',
            default: 0
        },
        cost: {
            type: 'number',
            minimum: 0,
            title: 'Cost',
            description: 'Giá vốn',
            default: 0
        },
        vat_sale: {
            type: 'number',
            minimum: 0,
            title: 'Vat Sale',
            description: 'VAT bán ra (%)',
            default: 0
        },
        vat_purchase: {
            type: 'number',
            minimum: 0,
            title: 'Vat Purchase',
            description: 'VAT mua vào (%)',
            default: 0
        },
        is_purchase: {
            type: 'boolean',
            title: 'Is Purchase',
            description: 'Có thể mua',
            default: false
        },
        is_sale: {
            type: 'boolean',
            title: 'Is Sale',
            description: 'Có thể bán',
            default: true
        },
        is_manufacture: {
            type: 'boolean',
            title: 'Is Manufacture',
            description: 'Dùng để sản xuất',
            default: false
        },
        is_storable: {
            type: 'boolean',
            title: 'Is Storable',
            description: 'Theo dõi tồn kho',
            default: false
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            description: 'Lưu trữ',
            default: false
        },
        category_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Category Ids',
            description: 'Danh sách ID danh mục'
        },
        uom_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Uom Ids',
            description: 'Danh sách ID đơn vị phụ'
        }
    },
    type: 'object',
    required: ['name', 'sku'],
    title: 'ProductCreate'
} as const;

export const ProductPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name',
            description: 'Tên sản phẩm'
        },
        sku: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Sku',
            description: 'Mã sản phẩm'
        },
        image: {
            type: 'string',
            maxLength: 255,
            title: 'Image',
            description: 'Hình ảnh',
            default: ''
        },
        type: {
            type: 'string',
            enum: ['consu', 'service', 'combo'],
            title: 'Type',
            description: 'Loại sản phẩm (consu: hàng hoá, service: dịch vụ, combo: bộ)',
            default: 'consu'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description',
            description: 'Mô tả'
        },
        uom_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Uom Id',
            description: 'Đơn vị tính chính'
        },
        price: {
            type: 'number',
            minimum: 0,
            title: 'Price',
            description: 'Giá bán',
            default: 0
        },
        cost: {
            type: 'number',
            minimum: 0,
            title: 'Cost',
            description: 'Giá vốn',
            default: 0
        },
        vat_sale: {
            type: 'number',
            minimum: 0,
            title: 'Vat Sale',
            description: 'VAT bán ra (%)',
            default: 0
        },
        vat_purchase: {
            type: 'number',
            minimum: 0,
            title: 'Vat Purchase',
            description: 'VAT mua vào (%)',
            default: 0
        },
        is_purchase: {
            type: 'boolean',
            title: 'Is Purchase',
            description: 'Có thể mua',
            default: false
        },
        is_sale: {
            type: 'boolean',
            title: 'Is Sale',
            description: 'Có thể bán',
            default: true
        },
        is_manufacture: {
            type: 'boolean',
            title: 'Is Manufacture',
            description: 'Dùng để sản xuất',
            default: false
        },
        is_storable: {
            type: 'boolean',
            title: 'Is Storable',
            description: 'Theo dõi tồn kho',
            default: false
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            description: 'Lưu trữ',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        categories: {
            items: {
                '$ref': '#/components/schemas/CategoryInProduct'
            },
            type: 'array',
            title: 'Categories',
            default: []
        },
        uom: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/UomPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        uoms: {
            items: {
                '$ref': '#/components/schemas/UomPublic'
            },
            type: 'array',
            title: 'Uoms',
            default: []
        }
    },
    type: 'object',
    required: ['name', 'sku', 'id'],
    title: 'ProductPublic'
} as const;

export const ProductUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        sku: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sku'
        },
        image: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image'
        },
        type: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['consu', 'service', 'combo']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Type'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        uom_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Uom Id'
        },
        price: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price'
        },
        cost: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cost'
        },
        vat_sale: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vat Sale'
        },
        vat_purchase: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vat Purchase'
        },
        is_purchase: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Purchase'
        },
        is_sale: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Sale'
        },
        is_manufacture: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Manufacture'
        },
        is_storable: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Storable'
        },
        is_archived: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Archived'
        },
        category_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string',
                        format: 'uuid'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Ids'
        },
        uom_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string',
                        format: 'uuid'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Uom Ids',
            description: 'Danh sách đơn vị phụ'
        }
    },
    type: 'object',
    title: 'ProductUpdate'
} as const;

export const ProductsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProductPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProductsPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UomBaseSchema = {
    properties: {
        code: {
            type: 'string',
            maxLength: 20,
            title: 'Code',
            description: 'Mã đơn vị (VD: kg, lit, cai)'
        },
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name',
            description: 'Tên đơn vị tính'
        },
        relative_factor: {
            type: 'number',
            minimum: 0,
            title: 'Relative Factor',
            description: 'Hệ số quy đổi',
            default: 1
        },
        relative_uom_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Relative Uom Id',
            description: 'Đơn vị quy đổi'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            description: 'Lưu trữ',
            default: false
        }
    },
    type: 'object',
    required: ['code', 'name'],
    title: 'UomBase'
} as const;

export const UomCreateSchema = {
    properties: {
        code: {
            type: 'string',
            maxLength: 20,
            title: 'Code',
            description: 'Mã đơn vị (VD: kg, lit, cai)'
        },
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name',
            description: 'Tên đơn vị tính'
        },
        relative_factor: {
            type: 'number',
            minimum: 0,
            title: 'Relative Factor',
            description: 'Hệ số quy đổi',
            default: 1
        },
        relative_uom_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Relative Uom Id',
            description: 'Đơn vị quy đổi'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            description: 'Lưu trữ',
            default: false
        }
    },
    type: 'object',
    required: ['code', 'name'],
    title: 'UomCreate'
} as const;

export const UomPublicSchema = {
    properties: {
        code: {
            type: 'string',
            maxLength: 20,
            title: 'Code',
            description: 'Mã đơn vị (VD: kg, lit, cai)'
        },
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name',
            description: 'Tên đơn vị tính'
        },
        relative_factor: {
            type: 'number',
            minimum: 0,
            title: 'Relative Factor',
            description: 'Hệ số quy đổi',
            default: 1
        },
        relative_uom_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Relative Uom Id',
            description: 'Đơn vị quy đổi'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            description: 'Lưu trữ',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        base_uom: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/UomBase'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['code', 'name', 'id'],
    title: 'UomPublic'
} as const;

export const UomUpdateSchema = {
    properties: {
        code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Code'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        relative_factor: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Relative Factor'
        },
        relative_uom_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Relative Uom Id'
        },
        is_archived: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Archived'
        }
    },
    type: 'object',
    title: 'UomUpdate'
} as const;

export const UomsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UomPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UomsPublic'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const WarehouseCreateSchema = {
    properties: {
        code: {
            type: 'string',
            maxLength: 20,
            title: 'Code',
            description: 'Mã kho (VD: KHO01, WH-HCM)'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name',
            description: 'Tên kho'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address',
            description: 'Địa chỉ kho'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            description: 'Lưu trữ',
            default: false
        }
    },
    type: 'object',
    required: ['code', 'name'],
    title: 'WarehouseCreate'
} as const;

export const WarehousePublicSchema = {
    properties: {
        code: {
            type: 'string',
            maxLength: 20,
            title: 'Code',
            description: 'Mã kho (VD: KHO01, WH-HCM)'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name',
            description: 'Tên kho'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address',
            description: 'Địa chỉ kho'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            description: 'Lưu trữ',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['code', 'name', 'id'],
    title: 'WarehousePublic'
} as const;

export const WarehouseUpdateSchema = {
    properties: {
        code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Code'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        is_archived: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Archived'
        }
    },
    type: 'object',
    title: 'WarehouseUpdate'
} as const;

export const WarehousesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WarehousePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WarehousesPublic'
} as const;