"""add payment_methods table and pos_payment_method_link

Revision ID: 1c792eb7901a
Revises: d288823f77a1
Create Date: 2026-04-03 04:25:15.361245

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1c792eb7901a'
down_revision = 'd288823f77a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_methods',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pos_payment_method_link',
    sa.Column('pos_id', sa.Uuid(), nullable=False),
    sa.Column('payment_method_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pos_id'], ['pos_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pos_id', 'payment_method_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pos_payment_method_link')
    op.drop_table('payment_methods')
    # ### end Alembic commands ###
