"""update product uom and type logic

Revision ID: 9518e2b38e36
Revises: e5e0bb6231df
Create Date: 2026-04-02 09:53:05.982818

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9518e2b38e36'
down_revision = 'e5e0bb6231df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_uom_link',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('uom_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uom_id'], ['uoms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'uom_id')
    )
    op.add_column('products', sa.Column('uom_id', sa.Uuid(), nullable=True))
    op.add_column('products', sa.Column('is_storable', sa.Boolean(), nullable=False))
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.create_foreign_key(None, 'products', 'uoms', ['uom_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('products', 'is_storable')
    op.drop_column('products', 'uom_id')
    op.drop_table('product_uom_link')
    # ### end Alembic commands ###
