"""add color and image to product_categories

Revision ID: ca97f63297ce
Revises: 0304f6245c9b
Create Date: 2026-04-02 06:19:48.391033

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ca97f63297ce'
down_revision = '0304f6245c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_categories', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True))
    op.add_column('product_categories', sa.Column('image', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_categories', 'image')
    op.drop_column('product_categories', 'color')
    # ### end Alembic commands ###
