"""add kitchen screen module

Revision ID: dfce9d392be8
Revises: b948af7cc3c0
Create Date: 2026-04-03 06:09:28.365959

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dfce9d392be8'
down_revision = 'b948af7cc3c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kitchen_screens',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('pos_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pos_id'], ['pos_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kitchen_screen_product_category_link',
    sa.Column('kitchen_screen_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kitchen_screen_id'], ['kitchen_screens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('kitchen_screen_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kitchen_screen_product_category_link')
    op.drop_table('kitchen_screens')
    # ### end Alembic commands ###
