"""add fields to product table

Revision ID: e5e0bb6231df
Revises: ca97f63297ce
Create Date: 2026-04-02 06:32:50.445597

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e5e0bb6231df'
down_revision = 'ca97f63297ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE producttype AS ENUM ('storable', 'service', 'combo')")
    op.add_column('products', sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('products', sa.Column('image', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('products', sa.Column('vat_purchase', sa.Float(), nullable=False))
    op.add_column('products', sa.Column('vat_sale', sa.Float(), nullable=False))
    op.add_column('products', sa.Column('cost', sa.Float(), nullable=False))
    op.add_column('products', sa.Column('is_purchase', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('is_sale', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('is_manufacture', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('type', sa.Enum('storable', 'service', 'combo', name='producttype'), nullable=False))
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_column('products', 'type')
    op.execute("DROP TYPE producttype")
    op.drop_column('products', 'is_manufacture')
    op.drop_column('products', 'is_sale')
    op.drop_column('products', 'is_purchase')
    op.drop_column('products', 'cost')
    op.drop_column('products', 'vat_sale')
    op.drop_column('products', 'vat_purchase')
    op.drop_column('products', 'image')
    op.drop_column('products', 'sku')
    # ### end Alembic commands ###
